export default {
  //setters
  SET_EQUIPMENTS: 'SET_EQUIPMENTS',
  SET_EQUIPMENT: 'SET_EQUIPMENT',
  SET_EQUIPMENT_TYPES: 'SET_EQUIPMENT_TYPES',
  SET_PUT_EQUIPMENT_DATA: 'SET_PUT_EQUIPMENT_DATA',

  //actions
  FETCH_EQUIPMENT_DATA: 'FETCH_EQUIPMENT_DATA',
  POST_EQUIPMENT_DATA: 'POST_EQUIPMENT_DATA',
  SHOW_EQUIPMENT_DATA: 'SHOW_EQUIPMENT_DATA',
  PUT_EQUIPMENT_DATA: 'PUT_EQUIPMENT_DATA',
  DELETE_EQUIPMENT_DATA: 'DELETE_EQUIPMENT_DATA',
  FETCH_EQUIPMENT_TYPE_DATA: 'FETCH_EQUIPMENT_TYPE_DATA',

  //getters
  GET_EQUIPMENTS: 'GET_EQUIPMENTS',
  GET_EQUIPMENT: 'GET_EQUIPMENT',
  GET_EQUIPMENT_TYPES: 'GET_EQUIPMENT_TYPES',
  GET_PUT_EQUIPMENT_DATA: 'GET_PUT_EQUIPMENT_DATA',
}