version: '3.8'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: equip-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./back/src:/var/www/laravel_docker
      - ./back/nginx:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    links:
      - php-fpm
    networks:
      - others_my-net

  php-fpm:
    container_name: equip-php-fpm
    build:
      context: back/php
    restart: unless-stopped
    ports:
      - "9000:9000"
    working_dir: /var/www/laravel_docker
    volumes:
      - ./back/src:/var/www/laravel_docker
    networks:
      - others_my-net
      
  mysql:
    image: mysql:5.7
    container_name: equip_db
    ports:
      - "3306:3306"
    volumes:
      - equip-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_base
      MYSQL_PASSWORD: my_base
    networks:
      - others_my-net
      
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8030:8025
    networks:
      - others_my-net

  nodejs_react:
    image: node:16.14.0
    container_name: nodejs_react
    volumes:
      - ./front_react:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3006:3006
    tty: true
    stdin_open: true

  nodejs_vue:
    image: node:18.0.0
    container_name: nodejs_vue
    volumes:
      - ./front_vue:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    tty: true
      
networks:
  others_my-net:
    driver: bridge
    
volumes:
  equip-mysql-data:


