const counterConst = {
  NAME: 'COUNTER',

  //actions
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  COUNTER_INCREMENT_ASYNC: 'COUNTER_INCREMENT_ASYNC',
  COUNTER_DECREMENT_ASYNC: 'COUNTER_DECREMENT_ASYNC',

  //get state
  COUNTER_COUNT_STATE: 'COUNTER_COUNT_STATE',
}

export default counterConst