const authConst = {
  NAME: 'EQUIPMENT',

  //actions
  FETCH_EQUIPMENT: 'FETCH_EQUIPMENT',
  PUT_EQUIPMENT: 'PUT_EQUIPMENT',
  DELETE_EQUIPMENT: 'DELETE_EQUIPMENT',
  FETCH_EQUIPMENT_LIST: 'FETCH_EQUIPMENT_LIST',
  POST_EQUIPMENT_LIST: 'POST_EQUIPMENT_LIST',
  FETCH_EQUIPMENT_TYPE_LIST: 'FETCH_EQUIPMENT_TYPE_LIST',

  //get state
  GET_EQUIPMENT_STATE: 'GET_EQUIPMENT_STATE',
}

export default authConst